version: '3.8'

services:
  redis-master:
    image: redis:7.0-alpine
    container_name: redis-master
    ports:
      - "6379:6379"

  redis-slave:
    image: redis:7.0-alpine
    container_name: redis-slave
    depends_on:
      - redis-master
    command: ["redis-server", "--slaveof", "redis-master", "6379"]

  redis-slave2:
    image: redis:7.0-alpine
    container_name: redis-slave2
    depends_on:
      - redis-master
    command: ["redis-server", "--slaveof", "redis-master", "6379"]

  redis-sentinel1:
    image: redis-sentinel:v4
    container_name: redis-sentinel1
    depends_on:
      - redis-master

  redis-sentinel2:
    image: redis-sentinel:v4
    container_name: redis-sentinel2
    depends_on:
      - redis-master

  redis-sentinel3:
    image: redis-sentinel:v4
    container_name: redis-sentinel3
    depends_on:
      - redis-master